server:
  port: 8001
  servlet:
    context-path: /quartz-test-service
spring:  
  application:
    name: quartz-test-service
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=Hongkong&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: test.springboot.bean
  config-location: classpath:mybatis/mybatis-config.xml

quartz:
  enabled: true
task:
  delayTime: 2
