spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 12331
#    password: 
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#    consumer:
#      group-id: 0
#      auto-commit-interval: 100
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    listener:
#      concurrency: 3

logging:
  config: classpath:logback.xml

mybatis-plus:
  type-aliases-package: test.spring.tests.bean
